language: python
sudo: required
services:
- docker
before_install:
- docker pull f5devcentral/containthedocs:latest
install: 
- pip install awscli --upgrade
script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh
  #- aws s3 cp versions.json s3://clouddocs.f5.com/containers/versions.json

# DEPLOY TO STAGING
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: clouddocs.f5networks.net
  local_dir: docs/_build/html
  upload_dir: containers/v4.0.0
  on:
    branch: version-testing
    repo: F5Networks/f5-ci-docs
